### PR TITLE
Add QmlPromise class

### PR DESCRIPTION
**Pull request by nathanielhourt**
This class is useful for creating promises in C++ which are then passed
to QML. QML is then able to call .then() on these promises to add
continuations. The C++ QmlPromise can then be used to resolve or reject
the promise, thus allowing QML to be notified when a C++ asynchronous
operation finishes.

### CODE REVIEW

**Comment by nathanielhourt** [comment]
Oh, and to be clear, this code is provided with no licensing strings attached. Feel free to include it in your standard Apache 2.0 licensed distribution.

**Comment by nathanielhourt** [comment]
Apparently Travis's compiler is ancient. I can't help that.

**Comment by benlau** [comment]
cool. It is interesting. Should be a good feature. Thx!

Since I am quite busy in this few day, I only take a quick glance on your code. Here is my comment:

1)  Initialize member attribute in contructor.

../../qmlpromise.h:16:25: sorry, unimplemented: non-static data member initializers

The g++ version in travis is still 4.6, it don't support to initialize non-static data member in class declaration. Please move the initializer to class constructor.

2) The ownership of internal promise

I think the internal promise should be owned by C++. At long as the C++ class is alive, it should not be destroyed. Once the C++ class is destroyed, it may move it to Qml ownership scope? (I am not sure do it works)

What do you think?

p.s My thought may not be correct since I only took a quick glance

3) Naming convention

C++ class in QuickPromise use the prefix of "QP". Please rename your class to fit the naming convention. 

Good job and thx.

**Comment by nathanielhourt** [comment]
1. Became moot when applying suggestion 2
2. Great idea! Much cleaner than my solution. Simplified the code nicely. :)
3. Done.

**Comment by benlau** [comment]
Hi @nathanhourt,

So far It looks fine. Good job! 

However, your unit test is not executed by travis. Do you familiar with travis? If not, I will first accept the pull request and setup travis by myself.

**Comment by nathanielhourt** [comment]
In retrospect, I probably shouldn't have used Qt's unit testing framework for my tests, since the things I'm testing don't fit cleanly into either the normal unit testing framework (not designed for QML) or the QML testing framework (doesn't support C++), and generally results in the whole thing being a hack. Right now integrating it into Travis won't matter since it always returns 0 at exit. I'll poke at it and see if it can be automated.

**Comment by nathanielhourt** [comment]
Looks like Qt's unit testing fw works acceptably well for what I wanted; I just needed to do away with the convenience macro. At this point, the test framework sleeps for 50ms to let promises resolve; I'm not sure if there's a better way to do that. It works in travis finally, though, so everything should be good to go.

**Comment by benlau** [comment]
Excellent. Good job.

**Comment by benlau** [comment]
Hi @nathanhourt ,

I have a question about the class. What is your expected use-case? (e.g how it solve user's problem?)

**Comment by nathanielhourt** [comment]
Prior to the introduction of this class, I was not aware of any convenient mechanism by which QML code could invoke an asynchronous operation implemented in C++ and receive a promise for the result of that operation.

For example, suppose an app contains a form in the QML-based GUI which the user completes, and clicks a button to submit to a server over the network. Furthermore, suppose that the networking is implemented in C++. Here is an example of how that can go, using my class:

From the QML perspective: The QML calls a method on a C++ object passing the data from the form as arguments, and that method returns a promise for the server's response. The GUI then shows some kind of "Loading" animation while waiting for the network. When the promise resolves, the GUI can proceed to the next page. Alternatively, if the promise fails, the GUI can display an error and return to the form.

From the C++ perspective: A method to submit a request to the server is invoked on an object responsible for managing the connection to the server. The method assembles the request, serializes it, and sends it to the server, then creates a `QPPromise` to carry the server's response when it arrives. The method stores the `QPPromise` in its internal state to be resolved when the response arrives, and returns the promise to the caller. When the server's response arrives from the network, the class looks up the QPPromise corresponding to that response and resolves/rejects it according to the server's response.

Does that clear things up?

**Comment by benlau** [comment]
I see. It should be clear enough. In fact, I am planning to release a new version and thinking about how to explain your class to users.

**Pull request merged**
